name: CI

on:
  push:
    branches: "master"

jobs:
  run:
    name: Pangeo-Forge CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Setup Python
        uses: actions/setup-python@v2.1.0
        with:
          python-version: 3.7
          architecture: x64
      - uses: actions/cache@v2.1.1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/*requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
            python -m pip install -r requirements.txt
      - name: Authenticate with DockerHub
        run: |
            echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
      - name: Run Pipeline
        run: |
            # Login
            prefect auth login --token ${{ secrets.PREFECT_ACCESS_TOKEN }}

            # Register flow
            python recipe/pipeline.py

            # Run flow
            prefect run flow --name=terraclimate --project=pangeo-forge
